name: Deploy to Pages
on:
  push:
    branches:
      - master
    paths:
      - 'src/**'
      - 'public/**'
jobs:
  build-and-deploy:
    env:
      ENABLE_AUTO_DEPLOY: ${{ !!secrets.ENABLE_AUTO_DEPLOY }}
      ENABLE_AUTO_DEPLOY_TO_REMOTE: ${{ !!secrets.REMOTE_URL }}
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@master
      - name: Cache node_modules
        uses: actions/cache@master
        with:
          path: node_modules
          key: ${{ runner.OS }}-modules-${{ hashFiles('package-lock.json') }}
          restore-keys: ${{ runner.OS }}-modules-
      - name: Build and Deploy to GitHub Pages
        if: env.ENABLE_AUTO_DEPLOY == 'true'
        uses: JamesIves/github-pages-deploy-action@releases/v2
        env:
          ACCESS_TOKEN: ${{ secrets.GITHUB_TOKEN }}
          BRANCH: gh-pages
          FOLDER: dist
          CNAME: ${{ secrets.CNAME }}
          BUILD_SCRIPT: npm install && npm run build
      - name: Deploy to Remote Pages
        if: env.ENABLE_AUTO_DEPLOY == 'true' && env.ENABLE_AUTO_DEPLOY_TO_REMOTE == 'true'
        uses: Tsuk1ko/git-https-push-action@master
        with:
          remoteUrl: ${{ secrets.REMOTE_URL }}
          forcePush: true
